UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-check-square-o' WHERE `IdMenuDetalle`='12';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-cog' WHERE `IdMenuDetalle`='1';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-cogs' WHERE `IdMenuDetalle`='2';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-crop' WHERE `IdMenuDetalle`='3';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-users' WHERE `IdMenuDetalle`='25';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-crop' WHERE `IdMenuDetalle`='24';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-crop' WHERE `IdMenuDetalle`='23';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-group' WHERE `IdMenuDetalle`='4';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-dollar' WHERE `IdMenuDetalle`='5';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Codigo F910', `Icono`='fa fa-bookmark-o' WHERE `IdMenuDetalle`='6';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Codigo OVISSS', `Icono`='fa fa-bookmark-o' WHERE `IdMenuDetalle`='7';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Codigo SEPP', `Icono`='fa fa-bookmark-o' WHERE `IdMenuDetalle`='8';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Config General', `Icono`='fa fa-gear' WHERE `IdMenuDetalle`='9';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-home' WHERE `IdMenuDetalle`='10';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-folder' WHERE `IdMenuDetalle`='11';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-folder-o' WHERE `IdMenuDetalle`='14';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Inst Previsional', `Icono`='fa fa-folder-open-o' WHERE `IdMenuDetalle`='13';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Tipo Documentos', `Icono`='fa fa-bars' WHERE `IdMenuDetalle`='15';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-bars' WHERE `IdMenuDetalle`='16';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-pencil' WHERE `IdMenuDetalle`='17';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-pencil' WHERE `IdMenuDetalle`='18';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-pencil' WHERE `IdMenuDetalle`='19';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-pencil' WHERE `IdMenuDetalle`='20';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-user' WHERE `IdMenuDetalle`='21';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-clock-o' WHERE `IdMenuDetalle`='22';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Cat de Cuentas', `Icono`='fa fa-bank' WHERE `IdMenuDetalle`='26';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Dep Empresariales', `Icono`='fa fa-building' WHERE `IdMenuDetalle`='27';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-building-o' WHERE `IdMenuDetalle`='28';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-list' WHERE `IdMenuDetalle`='29';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-list-ul' WHERE `IdMenuDetalle`='30';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-indent' WHERE `IdMenuDetalle`='31';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Peach no Depend', `Icono`='fa fa-outdent' WHERE `IdMenuDetalle`='32';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Peach - Planilla', `Icono`='fa fa-th-list' WHERE `IdMenuDetalle`='33';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='34';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='35';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='36';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='37';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='38';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='39';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='40';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='41';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='42';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='43';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='44';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-arrow-circle-o-right' WHERE `IdMenuDetalle`='45';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='46';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Cons Dependiente', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='47';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Cons no Depent', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='48';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='Planilla no Depent', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='49';
UPDATE `db_planilla`.`menudetalle` SET `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='50';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='RPT Accion Personal', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='51';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='RPT de Propinas', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='52';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='RPT  F910 Anual', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='53';
UPDATE `db_planilla`.`menudetalle` SET `DescripcionMenuDetalle`='RPT SEPP', `Icono`='fa fa-tasks' WHERE `IdMenuDetalle`='54';
